
version: 2

models:
  - name: src_ecommerce
    description: "copy from bigquery-public-data"
    tables:
      - name: inventory_items
      - name: order_items
      - name: orders
      - name: products
      - name: users
